os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
      - lib32stdc++6
before_script:
  - git clone https://github.com/flutter/flutter.git --depth 1
  - cd flutter
  - git clean -xfd
  - git stash save --keep-index
  - git stash drop
  - git pull
  - cd ..
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test --coverage --coverage-path=lcov.info
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
